name: .NET Core CI

on: [push, pull_request]

jobs:
  build:
    name: .NET on ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1

    - name: Build CLI
      run: dotnet build -c Release ./Decompiler/Decompiler.csproj

    - name: Build Library
      run: dotnet build -c Release ./ValveResourceFormat/ValveResourceFormat.csproj

    - name: Run tests
      run: dotnet test -v normal ./Tests/Tests.csproj
