name: .NET Core CI

on: [push, pull_request]

jobs:
  build:
    name: .NET on ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2.3.1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1

    - name: Build CLI
      run: dotnet build -c Release ./Decompiler/Decompiler.csproj

    - name: Build Library
      run: dotnet build -c Release ./ValveResourceFormat/ValveResourceFormat.csproj

    - name: Build GUI
      if: matrix.os == 'windows-latest'
      run: dotnet build -c Release ./ValveResourceFormat/ValveResourceFormat.csproj

    - name: Run tests
      run: dotnet test -v normal ./Tests/Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput='./lcov.info' /p:Include="[ValveResourceFormat*]*"

    - name: Pack nupkg
      run: dotnet pack --configuration release ValveResourceFormat/ValveResourceFormat.csproj

    - name: Publish GUI
      if: matrix.os == 'windows-latest'
      run: dotnet publish --configuration Release -p:PublishSingleFile=true --runtime win-x64 GUI/GUI.csproj

    - name: Publish Decompiler (Windows)
      if: matrix.os == 'windows-latest'
      run: dotnet publish --configuration Release -p:PublishSingleFile=true --runtime win-x64 Decompiler/Decompiler.csproj

    - name: Publish Decompiler (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: dotnet publish --configuration Release -p:PublishSingleFile=true --runtime linux-x64 Decompiler/Decompiler.csproj

    - name: Upload GUI
      uses: actions/upload-artifact@v2
      if: matrix.os == 'windows-latest'
      with:
        name: VRF GUI
        path: GUI/bin/Release/win-x64/publish

    - name: Upload nupkg
      uses: actions/upload-artifact@v2
      if: matrix.os == 'windows-latest'
      with:
        name: nupkg
        path: 'ValveResourceFormat/bin/Release/*.nupkg'

    - name: Upload Decompiler (Windows)
      uses: actions/upload-artifact@v2
      if: matrix.os == 'windows-latest'
      with:
        name: Decompiler for Windows
        path: Decompiler/bin/Release/win-x64/publish

    - name: Upload Decompiler (Linux)
      uses: actions/upload-artifact@v2
      if: matrix.os == 'ubuntu-latest'
      with:
        name: Decompiler for Linux
        path: Decompiler/bin/Release/linux-x64/publish

    - name: Upload test coverage
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./Tests/lcov.info
        flag-name: run-${{ matrix.test_number }}
        parallel: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
